name: swiss_tool
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  device_info_plus: ^10.0.0
  network_info_plus: ^5.0.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  path_provider: ^2.1.1
  audioplayers: ^5.2.1
  record: ^5.1.0
  record_windows: ^1.0.1
  crypto: ^3.0.7
  url_launcher: ^6.3.2
  file_picker: ^10.3.10

dependency_overrides:
  record_linux: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

# --- İKON AYARLARI BURADA KALABİLİR (Bu ayrı bir başlık) ---
flutter_launcher_icons:
  android: false
  ios: false
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256

# --- FLUTTER AYARLARI (BİRLEŞTİRİLDİ) ---
flutter:
  uses-material-design: true

  # Asset'leri buraya, aynı flutter başlığının altına ekliyoruz
  assets:
    - assets/speedtest.exe
